### ISSUE TITLE
Working with 3D Slicer

### ISSUE THREAD

**Issue by santiagooli** [NVIDIA/ai-assisted-annotation-client#104]
I´m a doctor trying to use 3D Slicer for jaw segmentation. I kew about Nvidia AAIA just recently and installed the plugin. I don´t know how to set the server (too many coding lines that I do not know how to use), and living the space blank does not let me try. I would like to use my own dicom sets but trying to use the module  scapes my computer skills. Is there any plug an play way to perform the AI segmetations without the tedious other options slicer provides_

**Comment by tangy5** [comment]
@santiagooli Thank you for using MONAI Label and 3D Slicer for segmentation tasks. 
Recently, we updated documentation on starting using MONAI Label with 3D Slicer. 

Please see this page for installation details, this includes a step-by-step guide for setting up the server, plugins, and communicating with 3D Slicer for AI tools.
https://docs.monai.io/projects/label/en/latest/installation.html

In addition: the tutorial quickstart page introduces the Radiology App as an example: 
https://docs.monai.io/projects/label/en/latest/quickstart.html#tutorial-1-radiology

More documentation in the Github can be found here: https://github.com/tangy5/MONAILabel/tree/monailabel_readme_update

Thank you again, let us know if there are further questions, we are appreciative of all user experience and feedback for improving MONAI Label with 3D Slicer!

Yucheng

**Comment by diazandr3s** [comment]
Thanks for opening this issue, @santiagooli.

Could you please add more information on the jaw segmentation use case? How many images you'd like to annotate? In which format are those images?

In a previous Slicer Hackathon, we has a use case in which we used MONAI Label to perform teeth and jaw segmentation: https://projectweek.na-mic.org/PW36_2022_Virtual/Projects/AutomaticSegmentationofTeethandAlveolarBone/

Is your use case similar to this one?

We assume MONAI Label users are familiar with Slicer. If this is not the case, you may find helpful this demo: https://youtu.be/wtiEe_jiUzg?t=2206 

Here is also a video tutorial to start using MONAI Label: https://www.youtube.com/watch?v=8y1OBQs2wis&list=PLtoSVSQ2XzyD4lc-lAacFBzOdv5Ou-9IA

As @tangy5 said, please don't hesitate to post questions in the discussion section here: https://github.com/Project-MONAI/MONAILabel/discussions

Hope this helps,

**Comment by santiagooli** [comment]
Dear Andres

I use jaw segmentation to produce stl files and later use them in Blender
to plan implant treatments. Usually a dicom batch has from 250 to 350
images. I’m new with labelling but usually I just want to isolate the jaw,
maxilla and sinuses. One of the problems is to isolate the scattering from
metal restorations as it has to be removed by hand slice by slice… hence my
interest for this AI technique.
All I want is to use my own dicom files with the AI tools. I followed the
PyPi install instructions but when I run it to activate the server it fails
to find the radiology directory and if I go to slicer, if I try to refresh
the server it is denied…
My knowledge of python is basically copy and paste… so a little help is
needed here….
Best Regards
Santiago

**Comment by SachidanandAlle** [comment]
Please raise any issues/questions related to MONAILabel on corresponding github:
https://github.com/Project-MONAI/MONAILabel

**Comment by diazandr3s** [comment]
Hi @santiagooli 

Thanks for sharing the details of the dataset and task.

Have you followed the instructions given in the [Readme](https://github.com/Project-MONAI/MONAILabel/blob/main/README.md)?

> # download radiology app and sample dataset
> monailabel apps --download --name radiology --output apps
> monailabel datasets --download --name Task09_Spleen --output datasets
> 
> # start server using radiology app with deepedit model enabled
> monailabel start_server --app apps/radiology --studies datasets/Task09_Spleen/imagesTr --conf models deepedit


Did you follow the step-by-step tutorial explained [here](https://www.youtube.com/watch?v=8y1OBQs2wis&list=PLtoSVSQ2XzyD4lc-lAacFBzOdv5Ou-9IA)? 

If yes and you're still facing the same issue, I'd recommend you to please create and issue or open a discussion as @SachidanandAlle recommended: https://github.com/Project-MONAI/MONAILabel/issues - and add the logs or errors you face.

Thanks!

**Comment by santiagooli** [comment]
Yes I did follow the tutorial.
 I did struggle some places with the grammar but at the end all was looking like the video screen, just the server never started. I tried to work with Slicer and when I tried to refresh the server a pop up appeared saying it was not possible and the info said the original computer actively refuse it.
I will unistall it and will try again...
Thanks

**Comment by SachidanandAlle** [comment]
Closing this issue.. and lets take the discussion in MONAILabel repo instead

**Comment by diazandr3s** [comment]
> Closing this issue.. and lets take the discussion in MONAILabel repo instead

https://github.com/Project-MONAI/MONAILabel
