### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by DrBroHan** [NVIDIA/ai-assisted-annotation-client#105]
I try to use the NVIDIA AIAA today and it suddenly stopped working.
Seems to fail to connect to the public server. Is there any ETA on fix?
Please advise.

I would love to setup my own server but I won't be able to do that till next year due to funding issue.

**Comment by SachidanandAlle** [comment]
i suggest to use monailabel and run it on your box.. like laptop.. by just doing pip install..
NVIDIA AIAA is under deprecation.  MONAILabel provides AIAA + lot of other features..
https://github.com/Project-MONAI/MONAILabel
