### ISSUE TITLE
Failed to execute 'dextr3d' on Nvidia AIAA Server

### ISSUE THREAD

**Issue by ChenFeiL** [NVIDIA/ai-assisted-annotation-client#14]
Hello Sir,
I tried the AI Segmentation function NVIDIA AI-Assisted Annotation in MITK 2018.04.2, but an error occurred "Failed to execute 'dextr3d' on Nvidia AIAA Server, nvidia.aiaa.error.101, description: Failed to communicate to AIAA Server". Could you please help me with this problem? Thank you.

**Comment by SachidanandAlle** [comment]
You need AIAA Server setup and running (docker released by NVIDIA).  In that case, you can configure the server URL by following Ctrl+P or Preferences.

If Server is up and running, and still you are not able to find the issue, MITK console logs can help to debug the issue.

**Comment by ChenFeiL** [comment]
I got it, thank you very much.
