### ISSUE TITLE
 Failed to communicate to AIAA Server

### ISSUE THREAD

**Issue by amberhappy** [NVIDIA/ai-assisted-annotation-client#21]
I install NvidiaAIAAClient-1.0.1-win64.exe and run the example.cpp in VS2015(win10),but got the error:
"14:45:50 [ERROR] [curlutils.cpp:83 - doGet()] Host not found: my-aiaa-server.com
nvidia::aiaa::exception => nvidia.aiaa.error.101; description: Failed to communicate to AIAA Server"

And, i am working with MITK, what should i set for server URI?

Thank you very much!

**Comment by SachidanandAlle** [comment]
`nvidiaAIAAListModels` -h  
will list u the options..

otherwise you can try:
`nvidiaAIAAListModels` -server http://my-aiaa-server.com/v1

**Comment by SachidanandAlle** [comment]
I am closing the issue (guessing that it's solved in your case;  if not then reopen it again)
