### ISSUE TITLE
Slicer: Moving Server Input Fields To Application Settings

### ISSUE THREAD

**Issue by SachidanandAlle** [NVIDIA/ai-assisted-annotation-client#23]
From @bsmarine
------------------

Ideally, there would be a workflow possibly like this: user selects model they would like to use under "Auto Segmentation" and "Annotation" (which would only show those available), then the model is fetched when selected and a new Segment node is made automatically. Thoughts?

Currently, I think it's tough to move the AIAA Server Info off this screen since model needs to be fetched only after an organ segmentation is manually created that corresponds to an available model on the server.

<img width="543" alt="Screen Shot 2019-08-13 at 4 52 16 PM" src="https://user-images.githubusercontent.com/20938393/62976773-5b67bc00-bdeb-11e9-8610-76fc29f7a560.png">

**Comment by bsmarine** [comment]
If feasible, this proposed workflow would be a solid improvement

**Comment by SachidanandAlle** [comment]
Closing this issue as the required changes are added to slicer

- Moved AIAA server settings into Application Settings
- On click/select/change segment, corresponding list of models are pre-fetched from AIAA server for annotation/segmentation (instead of user clicks *Fetch Models* explicitly)
