### ISSUE TITLE
Slicer plugin submission to Slicer's Extension manager

### ISSUE THREAD

**Issue by lassoan** [NVIDIA/ai-assisted-annotation-client#41]
It's great to see all the progress with the Slicer plugin.

Would you like to make the extension downloadable from Slicer's Extension manager? It would make the installation much easier (few mouse clicks).

For both Slicer stable (4.10.2) and preview releases?

Should the extension manager to automatically fetch the latest master version every night from this repository's master branch? (this is usually the recommended way for actively developed extensions, but if you prefer you can choose a designated release branch or a fixed git tag instead).

**Comment by SachidanandAlle** [comment]
This shall be really awesome.  It will also helpful for users to try in upcoming RSNA demo (I guess it's next week).  We are expecting users want to try NVIDIA AIAA segmentation using 3D Slicer.

Now we have moved everything into master branch.  So, I think we should fetch from master version every night as you suggested.

**Comment by bsmarine** [comment]
Phenomenal to see this progress! A Slicer extension would be terrific.

Thanks to all who helped make this possible.

**Comment by lassoan** [comment]
Extension has been submitted to Slicer's extension index (both latest stable and preview). We can test tomorrow.

**Comment by lassoan** [comment]
Confirmed that the AIAA plugin can be downloaded via Slicer's extension manager:

![image](https://user-images.githubusercontent.com/307929/69810125-31c77a80-11b9-11ea-8c5c-78c246c24dd6.png)
