### ISSUE TITLE
[Feature request] Integrate object detection

### ISSUE THREAD

**Issue by tbuikr** [NVIDIA/ai-assisted-annotation-client#49]
Thank your team for the cool project!

The project currently supports classification, segmentation tasks. Do you have any plan to support the detection task for example faster-rcnn using pytorch?

**Comment by SachidanandAlle** [comment]
yes.. we are having some roadmap to support py-torch in coming days.. plus classification etc..

**Comment by kidspro88** [comment]
Hi @SachidanandAlle, can we use classification in 3DSlicer now?

**Comment by kidspro88** [comment]
> yes.. we are having some roadmap to support py-torch in coming days.. plus classification etc..

Hi @SachidanandAlle, can we use classification in 3DSlicer now?

**Comment by SachidanandAlle** [comment]
> > yes.. we are having some roadmap to support py-torch in coming days.. plus classification etc..
> 
> Hi @SachidanandAlle, can we use classification in 3DSlicer now?

The support will be more at py-client or cpp-client for NVIDIA AIAA server (along with clara v3.0 release)

For slicer plugin, we don't have any e2e use-case to add classification task... however anyone can make use of py-client api.. and add the required user-interaction in slicer plugin

Clara v3 release will happen by last week of March 2020.. So with that you should be able to run classification/py-torch models etc..

**Comment by b02202050** [comment]
Hi, @SachidanandAlle
When will Clara V3 be released? Thanks.

**Comment by SachidanandAlle** [comment]
v3.0 version is available for nvidia clara.. you can find inference API for generic use.  that shall be helpful to run the classification models
