### ISSUE TITLE
C++ Client APIs + MITK plugin doesn't support ssh (https)

### ISSUE THREAD

**Issue by SachidanandAlle** [NVIDIA/ai-assisted-annotation-client#57]
Currently due to windows dependency build issue, in POCO SSL option is not enabled
Also MITK needs to support SSL support for it's internal POCO build to make it complete.

**Comment by kislinsk** [comment]
I am working on this, or to be precise, already testing it.

OpenSSL is now a general optional dependency of the MITK superbuild. If necessary (usually on Windows) use `OPENSSL_ROOT_DIR` to help CMake find OpenSSL. If it was found, Poco::Crypto and Poco::NetSSL will be built when bulding Poco in the MITK superbuild. On the MITK build level on Windows, the two CMake variables `MITK_OPENSSL_CRYPTO_SSL` and `MITK_OPENSSL_SSH_DLL` will pop up, to specify the actual OpenSSH DLLs. They are used to (a) copy the DLLs to MITK's binary folder and (b) package the DLLs when building an installer.

As soon as our build client are done building and succeeded in doing so, the changes will be pushed to the [release branch](https://github.com/MITK/MITK/tree/release/T28000-v2021.01) for MITK v2021.01.

**Comment by kislinsk** [comment]
Resolved on MITK-side.

**Comment by SachidanandAlle** [comment]
Thank you.  Will verify https access in MITK Workbench and then close the issue.
