### ISSUE TITLE
MITK Workbench: update NVIDIA clara plugin using latest version of AIAA Client

### ISSUE THREAD

**Issue by SachidanandAlle** [NVIDIA/ai-assisted-annotation-client#64]
@kislinsk

The new feature/plugin include deepgrow action in 2D tools.  Can we refresh MITK workbench with the latest AIAA client+MITK Plugin (which is v1.0.2 or master)

https://github.com/NVIDIA/ai-assisted-annotation-client/releases/

![Screenshot from 2020-03-11 05-27-42](https://user-images.githubusercontent.com/7339051/76416829-b9657d80-6393-11ea-98b0-9783b85cd907.png)

For reference (how deepgrow works): 
https://drive.google.com/open?id=1C88SrVjbiyFyDwsQhYwTKPmlgrmlxO8I

**Comment by SachidanandAlle** [comment]
We are planning to announce DeepGrow feature in GTC 2020 (I guess last week of March)

If existing MITK users want to explore this feature, new/updated binaries on MITK release page shall be helpful.

**Comment by kislinsk** [comment]
We can do this of course. :)

Is there any news regarding the server side? The feedback so far suggests that the current Workbench+Nvidia installer is nearly impossible to use by most interested users as it is out of their abilities to manually set up a server and configure models.

**Comment by SachidanandAlle** [comment]
like how slicer community has setup a public server (http://skull.cs.queensu.ca:8123) for a quick access to their users..

may be mitk can also host something like this.. and we can set it as default server uri in plugin configurations..

**Comment by kislinsk** [comment]
I would like to see Nvidia recognizing this as something to offer for the community as we are for example not qualified to support anything server-side like the models Nvidia trained or anything else specific to the method. :)

**Comment by SachidanandAlle** [comment]
NVIDIA is jointly working AWS integrations for AIAA.. this should help us to create a public access for AIAA soon for general audience...

**Comment by SachidanandAlle** [comment]
FYI: Nvidia clara v3.0 release is available for public use.  And NVIDIA team is working on Public AIAA server (through AWs) for general audience... so that they can try it in MITK Workbench etc..

**Comment by SachidanandAlle** [comment]
@kislinsk can we release MITK workbench with new feature (deepgrow).  Couple of customers are looking for this.  Currently I am sharing it through gdrive (as temporary solution) https://drive.google.com/drive/folders/1tdJ2TyG3PTpENwfvsfXmrmYAR_XPcATV?usp=sharing

**Comment by dinkelacker** [comment]
@SachidanandAlle Would you prefer master or v1.0.2?

**Comment by SachidanandAlle** [comment]
master branch 👍

**Comment by dinkelacker** [comment]
Done, I refreshed all the installers. ✔️

**Comment by SachidanandAlle** [comment]
Thank you very much.  I have verified the deepgrow feature on new Binaries.  All is good 👍
