### ISSUE TITLE
 [ERROR] [curlutils.cpp:83 - doGet()] Timeout: connect timed out: server_ip:5000

### ISSUE THREAD

**Issue by ytliang97** [NVIDIA/ai-assisted-annotation-client#66]
Hi, 

- version: v1.0.1 MacOS
- time: 4/3 22:48 (GMT+8)
- network: stable

When I tried the example code of Quick Start, I encountered some problem..

I typed `nvidiaAIAAListModels -h` to get default server URI, and this worked.

But when I typed `nvidiaAIAAListModels -server http://default_server_URI:5000/v1`, it soon failed.

Here is error message, it seems timeout. I also use `timeout` options 60 to 300, but it still failed quickly.
```
22:55:24 [ERROR] [curlutils.cpp:83 - doGet()] Timeout: connect timed out: 10.110.45.66:5000
nvidia::aiaa::exception => nvidia.aiaa.error.101; description: Failed to communicate to AIAA Server
```

Could anyone help me? Thanks!

By the way, how to upgrade client version to v1.0.2 or how to reinstall client?

**Comment by SachidanandAlle** [comment]
are able to open in browser: http://default_server_URI:5000/v1/models ?
from the same machine were you are trying to run the command..

or simple curl http://default_server_URI:5000/v1/models ?

upgrade should be simple..  just download the binaries and use it from anywhere..

**Comment by ytliang97** [comment]
No, I am not able to open in browser, and it says "No response".


Sorry for stupid question...because I already install v1.0.1

and I not sure if I install v1.0.2, would the machine will have both version or only v1.0.2 ?

Thanks!

**Comment by SachidanandAlle** [comment]
not able to in browser.. means.. you don't have AIAA server up and running...
On installation.. you can keep both by using a different prefix/installation path.. I guess better to use v1.0.2 instead of keeping older one..

**Comment by ytliang97** [comment]
oh my... Thank you very much! I thought there was a default online server running, and we can test client on it....
