### ISSUE TITLE
[Feature request] Integrate predictions of "external" models into the annotation server

### ISSUE THREAD

**Issue by MicPie** [NVIDIA/ai-assisted-annotation-client#68]
Thank you for setting up the AI assisted annotation client!

I was searching through the docs but I was not able to find a way to use predictions from models that are not loaded onto the annotation server. (For bringing my own models I only found the option to upload them in the TensorFlow checkpoint or TensorRT format.)

Are there other options to incorporate predictions of "external" models into the annotation server?

Thank you very much & kind regards
Michael

**Comment by SachidanandAlle** [comment]
You can do so... at-least PT (PyTorch) models..
https://docs.nvidia.com/clara/tlt-mi/clara-train-sdk-v3.0/aiaa/byom/byoi.html
