### ISSUE TITLE
Migrate Nvidia AIAA to MTK v2021.01

### ISSUE THREAD

**Issue by kislinsk** [NVIDIA/ai-assisted-annotation-client#78]
Hi,

we just created our [release branch](https://github.com/MITK/MITK/tree/release/T28000-v2021.01) for MITK v2021.01 and Nvidia AIAA needs a little migration to be compatible again. 

edit: Removed patch from description in favor of #79

**Comment by SachidanandAlle** [comment]
Possibly after this, we can add deepgrow 3D action into MITK Workbench.

**Comment by kislinsk** [comment]
@SachidanandAlle Cool, looking forward to the feature. :)

Is it possible to apply this patch so that we can utilize our CI the next days to also automatically create AIAA-enabled installers? That would be awesome!

**Comment by SachidanandAlle** [comment]
Yes.. that's wonderful.  We were looking for this automated process.  
Please give me a Pull request, I will help to merge it to master.

You have the required write access :)

**Comment by kislinsk** [comment]
> You have the required write access :)
Convenient. :)

**Comment by kislinsk** [comment]
Thanks @SachidanandAlle !
