### ISSUE TITLE
Inflammatory mass segmentation

### ISSUE THREAD

**Issue by jakubMitura14** [NVIDIA/ai-assisted-annotation-client#87]
Hello I am trying to perform a segmentation of inflammatory mass related to the infection of vascular graft infections. I try to use slicer Nvidia AIAA but I have 2 problems
1) I see that I need to use some concrete model like spleen... , but notnik fits my use case - I would just like it to find the structure based on the changes of density and multiple boundary points that I am supplying
2) even when I set some arbitrary model I get error that seems to be related to server (I am keeping the Nvidia AIAA server name blank to keep default )  error I get below

![image](https://user-images.githubusercontent.com/53857487/117862798-59b67b00-b293-11eb-876c-6b03a45720c6.png)

**Comment by lassoan** [comment]
There is an issue with the free server that we have set up that we expect to resolve within a few weeks (https://github.com/NVIDIA/ai-assisted-annotation-client/issues/62). You can either wait for that fix or set up your own Clara server.
