### ISSUE TITLE
How to build NVIDIA extension using CMake

### ISSUE THREAD

**Issue by akmal871026** [NVIDIA/ai-assisted-annotation-client#91]
Hi all, I have followed this instruction to plug in NVIDIA.

But, how to build it in CMake. (attached picture is my C Make)

this step I did not get the last step.

**This one: To build extension package, build 3D Slicer then configure ai-assisted-annotation-client project using CMake, defining these variables: -DSlicer_DIR:PATH=… -DNvidiaAIAssistedAnnotation_BUILD_SLICER_EXTENSION:BOOL=ON**

For developers
The plugin can be downloaded and installed directly from GitHub:

git clone GitHub - NVIDIA/ai-assisted-annotation-client: Client side integration example source code and libraries for AI-Assisted Annotation SDK
Open 3D Slicer: Go to Edit → Application Settings → Modules → Additional Module Paths
Add New Module Path: <FULL_PATH>/slicer-plugin/NvidiaAIAA
Restart
To build extension package, build 3D Slicer then configure ai-assisted-annotation-client project using CMake, defining these variables: -DSlicer_DIR:PATH=… -DNvidiaAIAssistedAnnotation_BUILD_SLICER_EXTENSION:BOOL=ON

**Comment by SachidanandAlle** [comment]
Building NVIDIA extension for 3D Slicer?

**Comment by lassoan** [comment]
For reference, @akmal871026 also asked this question on the Slicer forum: https://discourse.slicer.org/t/how-to-build-nvidia-extension-using-cmake/19681

To avoid parallel efforts, since the question is about building the Slicer plugin, I would recommend to continue the discussion at the Slicer forum.
