### ISSUE TITLE
Slicer 3D - Error Using nVIDIA AIAA - Prostate Model

### ISSUE THREAD

**Issue by marioboccia1992** [NVIDIA/ai-assisted-annotation-client#92]
Dear all,

Unfortunately I’m facing issue using nVIDIA AIAA module "clara_pt_prostate_mri_segmentation" in 3D Slicer.

Running the AI I get this error:

" Traceback (most recent call last):

File “C:/Users/M/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py”, line 410, in onClickSegmentation

extreme_points, result_file = self.logic.segmentation(in_file, session_id, model)

File “C:/Users/M/AppData/Local/NA-MIC/Slicer 4.11.20210226/NA-MIC/Extensions-29738/NvidiaAIAssistedAnnotation/lib/Slicer-4.11/qt-scripted-modules/SegmentEditorNvidiaAIAALib/SegmentEditorEffect.py”, line 1092, in segmentation

session_id=session_id,

File “C:\Users\M\AppData\Local\NA-MIC\Slicer 4.11.20210226\NA-MIC\Extensions-29738\NvidiaAIAssistedAnnotation\lib\Slicer-4.11\qt-scripted-modules\NvidiaAIAAClientAPI\client_api.py”, line 389, in inference

raise AIAAException(AIAAError.SERVER_ERROR, ‘Status: {}; Response: {}’.format(status, form))

NvidiaAIAAClientAPI.client_api.AIAAException: (3, ‘Status: 500; Response: b’{“error”:{“message”:[],“type”:“InferenceServerException”},“success”:false}\n’’) "

The prostate model probably fails because it requires two input images (T2 and ADC), but on Slicer I do not have the option to select two volumes.

Thank you very much !

M.

**Comment by SachidanandAlle** [comment]
you can run prostate input which has extra channel through slicer.. the best way you can run is by using direct APIs from AIAA.. when you visit http://127.0.0.1:5000/docs (where AIAA is running.. access /docs) to see the list of APIs and you can click try for inference api.. provide the input and get the output result (image)

**Comment by SachidanandAlle** [comment]
Closing this issue. Please use MONAILabel instead... feel free to raise any issue or start discussion over MONAILabel repo

**Comment by diazandr3s** [comment]
MONAI Label repo: https://github.com/Project-MONAI/MONAILabel
