### ISSUE TITLE
Error processing 3D annotations using dextr3D

### ISSUE THREAD

**Issue by abiswas97** [NVIDIA/ai-assisted-annotation-client#95]
We setup our AIAA server using the guide provided in https://docs.nvidia.com/clara/clara-train-sdk/aiaa/quickstart.html, and used the MITK workbench with AIAA client as downloaded from here - https://www.mitk.org/wiki/Downloads/NVIDIA_AI-Assisted_Annotation_Client. 

After setting our server to interact with the client, we are able to load models for segmentation, and run them successfully. However if we attempt to use the annotation option under 3D Segmentation, and provide six seed points, we get the error as below - 
```
Response: {"error":{"message":["invalid literal for int() with base 10: '[[41,71,64],[57,41,64],[71,85,64],[45,87,64],[67,67,64],[87,49,64]]'"],"type":"ValueError"},"success":false}
```

How should we proceed from here?

**Comment by SachidanandAlle** [comment]
Have you tried MONAI Label instead..?
https://github.com/Project-MONAI/MONAILabel/

**Comment by abiswas97** [comment]
I hadn't tried it, this looks promising. Thanks for the referral, I'll check this out!

**Comment by SachidanandAlle** [comment]
Closing this issue.. please use MONAILabel instead.. feel free to raise any issue or start discussion over MONAILabel repo
