### ISSUE TITLE
annotation ct liver not showing

### ISSUE THREAD

**Issue by muzahem** [NVIDIA/ai-assisted-annotation-client#96]
I wanted to try the liver segmentation with AIAA. I downloaded the extension and runned a sample data from 3d slicer. In "Segment from boundary points" the function "annotation ct liver" is not showing. 
How do I find the function "annotation ct liver" ?

**Comment by SachidanandAlle** [comment]
have you tried using MONAI Label?
https://github.com/Project-MONAI/MONAILabel/

**Comment by muzahem** [comment]
I have downloaded it. But I cant find tutorials for liver segmentation. I found only programming tutorials.

But why are many functions in AIAA not schwoing in the "Segment from boundary points"? In the turial more functions are showing.

**Comment by SachidanandAlle** [comment]
Not many models for annotation are there..
You can use deepgrow model instead for extreme points .. its better than annotation Models..

**Comment by SachidanandAlle** [comment]
Closing this issue.. please use MONAILabel instead.. feel free to raise any issue or start discussion over MONAILabel repo

**Comment by diazandr3s** [comment]
MONAI Label repo: https://github.com/Project-MONAI/MONAILabel
