### ISSUE TITLE
train or replace with own model 

### ISSUE THREAD

**Issue by jellywong88** [NVIDIA/ai-assisted-annotation-client#97]
I use the plugin-in in 3D slicer,  I want to segment tooth automatically, Is there any relevant instruction to train and replace the ai model in Auto-segmentation ?

**Comment by lassoan** [comment]
Development and user support efforts were moved from the AI-assisted annotation project to MONAILabel project. Please ask for advice at the MONAILabel discussion board: https://github.com/Project-MONAI/MONAILabel/discussions
